# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-05-26 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0036_add_asset_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiotrack',
            name='testvolume',
            field=models.FloatField(default=0, verbose_name='Test Volume'),
            preserve_default=False,
        ),
    ]
