# Generated by Django 3.0 on 2021-03-29 07:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rw', '0037_asset_file_and_loc_caption'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='email_author',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='asset',
            name='mediatype',
            field=models.CharField(choices=[('audio', 'audio'), ('photo', 'photo'), ('text', 'text')], default='audio', max_length=16),
        ),
        migrations.AlterField(
            model_name='asset',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tag',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rw.Project'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rw.TagCategory'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
