# Generated by Django 3.0 on 2021-05-13 10:52

import django.core.files.storage
from django.db import migrations, models
import rw.fields


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0039_auto_20210329_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='asset',
            name='file',
            field=rw.fields.ValidatedFileField(blank=True, help_text='Upload file', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/rwmedia/', location='/code/rwmedia'), upload_to='.'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='loc_caption',
            field=rw.fields.ValidatedFileField(help_text='Upload captions', null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/rwmedia/', location='/code/rwmedia'), upload_to='.'),
        ),
    ]
