# Generated by Django 3.0 on 2021-07-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rw', '0040_auto_20210513_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='submitted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
